### ISSUE TITLE
Not consistent accountId for IOS and Android

### ISSUE THREAD

**Issue by aanah0** [argyle-systems/argyle-plugin-react-native#2]
Hi guys! After the update, events for IOS and Android works well but have one issue

Listener `ArgyleSdk.onAccountConnected` return object like this for IOS
```
{
  accountId: "Uber"
  userId: "xxxxx-xx-xx-xxx-xxxx-xxxxxxx"
}
```

for Android the same listener return object like this
```
{
  accountId: "yyyy-yy-yyyyyyy-yyyyyy"
  userId: "xxxxx-xx-xx-xxx-xxxx-xxxxxxx"
}
```

I mean `accountId` for IOS looks like the name of the account and for Android looks like `uid`

I guess the expected return has to be like for both Android and IOS
```
{
  accountId: "yyyy-yy-yyyyyyy-yyyyyy"
  userId: "xxxxx-xx-xx-xxx-xxxx-xxxxxxx",
  accountName: "Uber"
}
```

**Comment by man4ik** [comment]
@gingyle @Shmulik-Argyle do you have any updates/fixes here?

**Comment by Varnius** [comment]
@aanah0 @man4ik
Hi, we are investigating this, will get back to you asap.

**Comment by Varnius** [comment]
We have identified the issue and are working on fixing it.

**Comment by Varnius** [comment]
@aanah0 @man4ik 
We have released a fix for this issue. Please update to Argyle 1.1.15

**Comment by man4ik** [comment]
@Varnius thank you.
Unfortunately, that's not the expected result. Ideally, we need to know provider name there. i.e Uber, Lyft, etc

**Comment by Audrius-Argyle** [comment]
@man4ik It is the correct pattern. You can use /accounts endpoint to get all the other data about that account.

**Comment by aanah0** [comment]
@Audrius-Argyle @Varnius
Can you please be sure that version `1.1.15` is available via NPM?

**Comment by Varnius** [comment]
@aanah0 
1.1.15 is a version of Cocoa pod we updated and not a version npm package (the fix was iOS side only). Sorry for not communicating that well enough.
Just do `cd ios` and `pod update` to update the pod to latest version (1.1.15). 
Cheers.
