### ISSUE TITLE
 In some cases Argyle is not loading the page with service account picker

### ISSUE THREAD

**Issue by man4ik** [argyle-systems/argyle-plugin-react-native#3]
Usually, it happens when the page is opened successfully, closed and opened again.
Even if it's an error on our implementation side would be good to know the reason.

Thank you for quick support

![photo_2020-01-07 15 15 33](https://user-images.githubusercontent.com/4026319/71910314-54ff2580-317a-11ea-83b8-852182c6066a.jpeg)

**Comment by Varnius** [comment]
@man4ik 
Thanks for reporting, looking into this.

**Comment by Varnius** [comment]
Hi @man4ik 
Can you check which version of our Android lib you are using - should be 1.1.5
Also, the correct way to initialize plugin is to call `ArgyleSdk.loginWith("plugin-key", "https://api-sandbox.argyle.io", "token")` once and then use `ArgyleSdk.start()` afterwards when you want to open the plugin screen.

**Comment by man4ik** [comment]
@Varnius thank you for the quick response.
* We double-checked the implementation. Everything there exactly as you mentioned before.
* We use the latest version of ArgyleSDK and do building on CI side. So every time it happens from scratch. 
* We do use various different devices. Samsungs s9, s10; goog pixel 3, 4, few others. 

Just to clarify we do have success loading of this page from time to time. 
Usually, we do have success for the first time we open the page, and it's failed when we do open this page second time. Restart the app is fixing the issue and allows us to open this screen once more.

**Comment by Varnius** [comment]
@man4ik 
We cannot currently reproduce this. Does the same issue appear when you run our example app?

**Comment by Varnius** [comment]
@man4ik 
Can you try running our react-native demo app:
https://github.com/argyle-systems/argyle-plugin-react-native-demo
Just don't forget to add valid plugin key in App.js before running it.

**Comment by man4ik** [comment]
@Varnius thanks for waiting here.
Can't reproduce this bug for a while. Let's close it
