### ISSUE TITLE
Event for closing SDK UI

### ISSUE THREAD

**Issue by aanah0** [argyle-systems/argyle-plugin-react-native#5]
Hello guys

How we can track events when SDK is closing? As I see in docs nothing about it

**Comment by Varnius** [comment]
@aanah0 There's no such event at the moment.
Your use case is to get some callback fired after the user closes SDK view, right?

**Comment by aanah0** [comment]
@Varnius right

**Comment by Varnius** [comment]
@aanah0 We added this to our backlog.

**Comment by aanah0** [comment]
@Varnius thanks. Can I ask about ETA?

**Comment by Varnius** [comment]
@aanah0 The current plan is to add this sometime in the period of next two weeks

**Comment by Varnius** [comment]
@aanah0 Added in 1.3.2
