### ISSUE TITLE
Swift compiler error after upgrading to the new XCode 11.4

### ISSUE THREAD

**Issue by knowbody** [argyle-systems/argyle-plugin-react-native#6]
Hey, I started experiencing the `Swift compiler error` after the upgrade to a newer XCode `version 11.4 (11E146)`

I'm using the latest: `"@argyleio/argyle-plugin-react-native": "^1.3.2",`

![image](https://user-images.githubusercontent.com/3802023/78421542-b8ed9900-7658-11ea-8437-fa9355b87f91.png)

**Comment by Varnius** [comment]
@knowbody Hi, we are aware of the issue, the fix should be out at the beginning of next week.

**Comment by Varnius** [comment]
Fixed in Argyle 1.3.5
Just navigate to /ios and run `pod update`, no need to update Argyle RN package.

**Comment by knowbody** [comment]
Thank you! That was quick! 🎉 👏
