### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by czystyl** [argyle-systems/argyle-plugin-react-native#8]
After upgrading pods using 1.3.2 version, I'm getting this screen:

![image](https://user-images.githubusercontent.com/10349378/79148812-72214100-7dc6-11ea-85e7-13a11326fbef.png)

before everything was working as expected. Let me know how I can help with debugging. 

`onError` handler returns `SERVER_ERROR`

**Comment by czystyl** [comment]
It's started working from today but three days was this screen.

Feel free to close the issues.

**Comment by Varnius** [comment]
@czystyl Hi, yes, we just fixed it and the causes are known. Thanks for reporting anyways!

**Comment by czystyl** [comment]
Thanks @Varnius for your quick support 🙌

**Comment by Varnius** [comment]
@czystyl Partially related to this issue - we added some further improvements, so please do upgrade to 1.4 jsut to be safe.

**Comment by czystyl** [comment]
Thanks, I'll do this.
